name: Release
description: "Release"
inputs:
  COMMAND_LIST:
    description: 'command argument'
    required: true
  ENV:
    description: 'Environment'
    default: 'test'
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  SLACK_TOKEN:
    description: 'SLACK_TOKEN'
    required: true
  SLACK_CHANNEL:
    description: 'SLACK_CHANNEL'
    required: true
  KEY_PASSPHRASE:
    description: 'KEY_PASSPHRASE'
    required: true
  KEY_ADDRESS:
    description: 'KEY_ADDRESS'
    required: true
  KEY_PRIVATE:
    description: 'KEY_PRIVATE'
    required: true
  NAVER_CLOUD_ACCESS_KEY:
    description: 'NAVER_CLOUD_ACCESS_KEY'
    required: true
  NAVER_CLOUD_SECRET_KEY:
    description: 'NAVER_CLOUD_SECRET_KEY'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  AWS_SESSION_TOKEN:
    description: 'AWS_SESSION_TOKEN'
    required: false
  ESIGNER_CREDENTIAL_ID:
    description: 'ESIGNER_CREDENTIAL_ID'
    required: true
  ESIGNER_USERNAME:
    description: 'ESIGNER_USERNAME'
    required: true
  ESIGNER_PASSWORD:
    description: 'ESIGNER_PASSWORD'
    required: true
  ESIGNER_TOTP_SECRET:
    description: 'ESIGNER_TOTP_SECRET'
    required: true
runs:
  using: 'docker'
  env:
    COMMAND_LIST: ${{ inputs.COMMAND_LIST }}
    ENV: ${{ inputs.ENV }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    SLACK_TOKEN: ${{ inputs.SLACK_TOKEN }}
    SLACK_CHANNEL: ${{ inputs.SLACK_CHANNEL }}
    KEY_PASSPHRASE: ${{ inputs.KEY_PASSPHRASE }}
    KEY_ADDRESS: ${{ inputs.KEY_ADDRESS }}
    KEY_PRIVATE: ${{ inputs.KEY_PRIVATE }}
    AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    AWS_SESSION_TOKEN: ${{ inputs.AWS_SESSION_TOKEN }}
    NAVER_CLOUD_ACCESS_KEY: ${{ inputs.NAVER_CLOUD_ACCESS_KEY }}
    NAVER_CLOUD_SECRET_KEY: ${{ inputs.NAVER_CLOUD_SECRET_KEY }}
    ESIGNER_CREDENTIAL_ID: ${{ inputs.ESIGNER_CREDENTIAL_ID }}
    ESIGNER_USERNAME: ${{ inputs.ESIGNER_USERNAME }}
    ESIGNER_PASSWORD: ${{ inputs.ESIGNER_PASSWORD }}
    ESIGNER_TOTP_SECRET: ${{ inputs.ESIGNER_TOTP_SECRET }}
  image: 'Dockerfile'
